[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "undici"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
